// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSxC0mYHKFAzggBz1DqEQ0ZenGJowJvTk',
    appId: '1:657892773380:web:484f899585d2095dc66f51',
    messagingSenderId: '657892773380',
    projectId: 'tut1-ae1e9',
    authDomain: 'tut1-ae1e9.firebaseapp.com',
    storageBucket: 'tut1-ae1e9.appspot.com',
    measurementId: 'G-LFPCEW58GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmyLhp7jdVkdzr5yC6b0PHbfcP8-9MxE',
    appId: '1:657892773380:android:e2015712f6c437c9c66f51',
    messagingSenderId: '657892773380',
    projectId: 'tut1-ae1e9',
    storageBucket: 'tut1-ae1e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHAwk9YDCxLDyuEWflJHm6CetYf9Pa8o',
    appId: '1:657892773380:ios:a039a0086cfdbbeac66f51',
    messagingSenderId: '657892773380',
    projectId: 'tut1-ae1e9',
    storageBucket: 'tut1-ae1e9.appspot.com',
    iosClientId: '657892773380-07mp8vo7rrc1mterinp4os3du2tf24k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuHAwk9YDCxLDyuEWflJHm6CetYf9Pa8o',
    appId: '1:657892773380:ios:a039a0086cfdbbeac66f51',
    messagingSenderId: '657892773380',
    projectId: 'tut1-ae1e9',
    storageBucket: 'tut1-ae1e9.appspot.com',
    iosClientId: '657892773380-07mp8vo7rrc1mterinp4os3du2tf24k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tut',
  );
}
